Delete button
The-Impastas/capstone pull request #16
Opened 2022-11-18 23:49 UTC by Heath-H

2022-11-18 23:49 UTC, rccalpito approved these changes
LGTM

2022-11-18 23:49 UTC, rccalpito approved these changes

2022-11-19 00:15 UTC, triciasykes requested changes
please delete the console.logs

2022-11-19 00:28 UTC, triciasykes approved these changes

2022-11-19 00:30 UTC, merged